### ISSUE TITLE
starting BLE failed!

### ISSUE THREAD

**Issue by paulvha** [sparkfun/Arduino_Apollo3#300]
As many other have experienced often you get an error: starting BLE failed! ( e.g. look at https://forum.sparkfun.com/viewtopic.php?f=169&t=54311). The issue is that the Apollo3 needs time to recover a reset. This can be solved with a short delay. Instead of putting this in ArduinoBLE (which might get a new update) , it is better in the Sparkfun library.
 
In **cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/hci/dual_chip/hci_cmd.c.** The routine **void HciResetCmd(void)** around line 1101, add before leaving the routine **delay(1000)**; 

What is a second in a life-time if solve HOURS for users ?

regards,
Paul

**Comment by oclyke** [comment]
Just did some poking around and testing of these BLE issues. The playing field seems fairly convoluted:

core ver. / ArduinoBLE ver. | 1.13 | 4abb537 | latest
------|------|---------|-------
**2.0.1** | baseline, works w/o modification | fail w/wo this mod, no serial output | fail w/wo this mod, no serial output
**2.0.2** | 'starting BLE failed' w/wo the mod | fail w/wo this mod, no serial output | fail w/wo this mod, no serial output

These results are not surprising to me either - modifications to the mbed core source files should not take effect in Arduino without regenerating the mbed core library (libmbed-os.a) and mbed is a layer below Arduino, so it cannot make use of the Arduino API 'delay' function. 

Our short-term solution will be to roll back to v2.0.1, ideally while still including the MicroMod support that was added in v2.0.2.

This discussion would be best continued in the [issue posted on the ArduinoBLE library](https://github.com/arduino-libraries/ArduinoBLE/issues/142) because it will receive more visibility from people who will be able to ensure compatibility.
